# Autogenerated wrapper script for AprilTags_jll for x86_64-linux-gnu
export libapriltag

JLLWrappers.@generate_wrapper_header("AprilTags")
JLLWrappers.@declare_library_product(libapriltag, "libapriltag.so.3")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libapriltag,
        "lib/libapriltag.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
